# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  username: ali2akbar5
  password: admin
  host: localhost
  port: 5432
  #min_messages: notice
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ali_api

test:
  <<: *default
  database: ali_api_test

production:
  <<: *default
  database: db/production.sqlite3